version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: tailgater-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:alpine
    container_name: tailgater-postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"